#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; IMAGE=$(get_app_image_name $APP)

if [ -f $DOKKU_ROOT/$APP/meteor-settings.json ]; then
  dokku_log_info1 "Load meteor-settings.json"

  id=$(docker create $IMAGE)
  test "$(docker wait $id)" -eq 0
  docker cp $DOKKU_ROOT/$APP/meteor-settings.json $id:/app/.profile.d/meteor-settings.json
  docker commit $id $IMAGE > /dev/null
  docker rm -v $id

  id=$(docker run -d $IMAGE /bin/bash -c "mkdir -p /app/.profile.d && echo 'export METEOR_SETTINGS=\"\`cat /app/.profile.d/meteor-settings.json\`\"' > /app/.profile.d/meteor-settings.sh")
  test "$(docker wait $id)" -eq 0
  docker commit $id $IMAGE > /dev/null
fi